name: Deploy Docs

on:
  push:
    branches:
      - main  # Change this to your main branch name
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: |
          sudo apt-get install graphviz
          sudo apt-get install -y doxygen
      - name: Set up Xerces-c
        run: |
          sudo apt install libxerces-c-dev
      - name: Set up schematicpp
        run: |
          git clone https://github.com/rajgoel/schematicpp.git
          cd schematicpp
          mkdir build
          cd build
          cmake ..
          make
          make install
      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make docs
          rm docs/html/*.md5
          rm docs/html/*.map
      - name: Deploy to GitHub Pages
        uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: docs/html
